CREATE TABLE `members` (
    id int(11) NOT NULL default NULL auto_increment ,
    deck_id int(11) default NULL ,
    user_id int(11) default NULL,
    created_at datetime NOT NULL default today,
    updated_at datetime NOT NULL default today,
    last_activity_id_requested int(11) default NULL,
    email_opt_out int(11) default '0',
    context_id int(11) default NULL,
    last_notification_time datetime default NULL,
    folder_id int(11) default NULL,
    is_deleted tinyint(1) default '0',
    admin tinyint(1) default '0',
    inviter_id int(11) default NULL,
    custom_message text default NULL,
    custom_subject text default NULL,
    action varchar(255) default NULL,
    send_email tinyint(1) default '1',
    expired tinyint(1) default '0',
)
